-- 드롭 (FK 의존 역순)
DROP TABLE IF EXISTS approval_attachment;
DROP TABLE IF EXISTS approval_line;
DROP TABLE IF EXISTS approval_document;
DROP TABLE IF EXISTS approval_form;

-- 1) 양식: form_code를 PK (자연키), AUTO ID 없음
CREATE TABLE approval_form (
  form_code        VARCHAR(20)  PRIMARY KEY,
  form_name        VARCHAR(100) NOT NULL,
  description      VARCHAR(255),
  content_template CLOB         NOT NULL,
  active           BOOLEAN      NOT NULL DEFAULT TRUE,
  created_at       TIMESTAMP    DEFAULT CURRENT_TIMESTAMP
);

-- 2) 문서: form_code를 FK로 참조
CREATE TABLE approval_document (
  doc_id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  form_code   VARCHAR(20) NOT NULL,
  title       VARCHAR(200) NOT NULL,
  content     CLOB,
  status      VARCHAR(20)  NOT NULL,
  created_by  BIGINT       NOT NULL,
  created_at  TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_doc_form_code
    FOREIGN KEY (form_code) REFERENCES approval_form(form_code)
);

-- 3) 결재선
CREATE TABLE approval_line (
  line_id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  doc_id      BIGINT NOT NULL,
  step_no     INT    NOT NULL,
  approver_id BIGINT NOT NULL,
  decision    VARCHAR(20) NOT NULL DEFAULT 'PENDING',
  decided_at  TIMESTAMP,
  comment     VARCHAR(500),
  CONSTRAINT fk_line_doc     FOREIGN KEY (doc_id) REFERENCES approval_document(doc_id),
  CONSTRAINT uq_line_doc_step UNIQUE (doc_id, step_no)
);

-- 4) 첨부
CREATE TABLE approval_attachment (
  att_id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  doc_id       BIGINT NOT NULL,
  filename     VARCHAR(255) NOT NULL,
  path         VARCHAR(500) NOT NULL,
  size         BIGINT NOT NULL,
  content_type VARCHAR(100) NOT NULL,
  created_at   TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_att_doc FOREIGN KEY (doc_id) REFERENCES approval_document(doc_id)
);

-- 인덱스
CREATE INDEX idx_doc_status ON approval_document(status);
CREATE INDEX idx_line_doc   ON approval_line(doc_id);
CREATE INDEX idx_att_doc    ON approval_attachment(doc_id);
