drop table if exists approval_document;

create table approval_document(
id		bigint generated by default as identity primary key,
title	varchar(200) not null,
content clob,
status	varchar(20) not null,
created_by	bigint not null,
created_at	timestamp default current_timestamp);